global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    dc: dc1

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'prometheus:9090'

  - job_name: 'node'
    static_configs:
      - targets:
        - 'prometheus:9100'
        - 'consul:9100'

  - job_name: 'consul_sd'
    consul_sd_configs:
      - server: http://consul:8500
        datacenter: dc1
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
